### ISSUE TITLE
Update repository fields in Cargo.toml

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/darwinia-common#185]
## Desc

For example, the manifest of `ethereum-primitives`:

```toml
[package]
name = "ethereum-primitives"
version = "0.6.1"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Ethereum primitives for Darwinia Relay"
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/" # Could not find ethereum-primitives by this repo
```
